kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: blob-pv-claim
spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
