apiVersion: v1
kind: Service
metadata:
  labels:
    app: enonic-xp
  name: enonic-xp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: wordpress
